pipeline {
  agent {
    kubernetes {
      label 'openpass-agent-pod'
      yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: openpass-build
    image: rbiegel/openpass-build:latest
    tty: true
    resources:
      limits:
        memory: "8Gi"
        cpu: "2"
      requests:
        memory: "8Gi"
        cpu: "2"
"""
    }
  }
  stages {
    stage('Build and test simulation core') {
      steps {
        container('openpass-build') {
          sh 'repo/utils/ci/scripts/10_prepare.sh'
          sh 'repo/utils/ci/scripts/15_dep_osi.sh'
          sh 'repo/utils/ci/scripts/16_dep_fmilibrary.sh'
          sh 'repo/utils/ci/scripts/20_configure.sh'
          sh 'repo/utils/ci/scripts/30_build.sh'
          sh 'repo/utils/ci/scripts/50_test.sh'
          sh 'repo/utils/ci/scripts/55_endtoend.sh'
          sh 'repo/utils/ci/scripts/90_pack_artifacts.sh'
        }
      }
    }
  }
}
