pipeline {
  agent {
    kubernetes {
      label 'openpass-agent-pod'
      yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: openpass-build
    image: rbiegel/openpass-build:latest
    tty: true
    resources:
      limits:
        memory: "16Gi"
        cpu: "4"
      requests:
        memory: "16Gi"
        cpu: "4"
"""
    }
  }
  stages {
    stage('Build and test simulation core') {
      steps {
        container('openpass-build') {
          // move repository to subfolder
          sh 'mkdir repo && find . -mindepth 1 -maxdepth 1 -not -name repo -print0 | xargs -0 mv -t repo'

          // get previous ccache
          script {
            try {
              copyArtifacts(projectName: currentBuild.projectName, filter: 'ccache.tar.gz')
            } finally {
            }
          }
          sh 'test -f ccache.tar.gz && tar zxf ccache.tar.gz'

          // run build steps
          sh 'repo/utils/ci/scripts/run_all.sh'

          // pack ccache
          dir(artifacts) {
            sh 'tar zcf ccache.tar.gz ../ccache'
          }
        }
      }
    }
  }
  post {
    always {
      archiveArtifacts allowEmptyArchive: true, artifacts: 'artifacts/**', followSymlinks: false
      junit allowEmptyResults: true, testResults: 'build/**/*_Tests.xml,repo/sim/tests/endToEndTests/pyOpenPASS/result_*.xml'
    }
  }
}

