HEADERS += \
    $$PWD/SystemComponentInputItemModel.h \
    $$PWD/SystemComponentInputMapModel.h \
    $$PWD/SystemComponentItemModel.h \
    $$PWD/SystemComponentManagerModel.h \
    $$PWD/SystemComponentMapModel.h \
    $$PWD/SystemComponentOutputItemModel.h \
    $$PWD/SystemComponentOutputMapModel.h \
    $$PWD/SystemComponentParameterItemModel.h \
    $$PWD/SystemComponentParameterMapModel.h \
    $$PWD/SystemComponentScheduleModel.h \
    $$PWD/SystemConnectionItemModel.h \
    $$PWD/SystemConnectionMapModel.h \
    $$PWD/SubsystemItemModel.h \
    $$PWD/SubsystemMapModel.h \
    $$PWD/SubsystemInputMapModel.h \
    $$PWD/SubsystemInputItemModel.h \
    $$PWD/SubsystemOutputMapModel.h \
    $$PWD/SubsystemOutputItemModel.h \
    $$PWD/SubsystemParameterMapModel.h \
    $$PWD/SubsystemParameterItemModel.h \
    $$PWD/SubsystemInputConnectionItemModel.h \
    $$PWD/SubsystemInputConnectionMapModel.h \
    $$PWD/SubsystemOutputConnectionItemModel.h \
    $$PWD/SubsystemOutputConnectionMapModel.h \
    $$PWD/SystemItemModel.h \
    $$PWD/SystemMapModel.h \
    $$PWD/SystemModel.h \
    $$PWD/SystemXMLBaseModel.h \
    $$PWD/SystemXMLLoadModel.h \
    $$PWD/SystemXMLSaveModel.h \
    $$PWD/SystemErrorModel.h

SOURCES += \
    $$PWD/SystemComponentInputItemModel.cpp \
    $$PWD/SystemComponentInputMapModel.cpp \
    $$PWD/SystemComponentItemModel.cpp \
    $$PWD/SystemComponentManagerModel.cpp \
    $$PWD/SystemComponentMapModel.cpp \
    $$PWD/SystemComponentOutputItemModel.cpp \
    $$PWD/SystemComponentOutputMapModel.cpp \
    $$PWD/SystemComponentParameterItemModel.cpp \
    $$PWD/SystemComponentParameterMapModel.cpp \
    $$PWD/SystemComponentScheduleModel.cpp \
    $$PWD/SystemConnectionItemModel.cpp \
    $$PWD/SystemConnectionMapModel.cpp \
    $$PWD/SubsystemItemModel.cpp \
    $$PWD/SubsystemMapModel.cpp \
    $$PWD/SubsystemInputMapModel.cpp \
    $$PWD/SubsystemInputItemModel.cpp \
    $$PWD/SubsystemOutputMapModel.cpp \
    $$PWD/SubsystemOutputItemModel.cpp \
    $$PWD/SubsystemParameterMapModel.cpp \
    $$PWD/SubsystemParameterItemModel.cpp \
    $$PWD/SubsystemInputConnectionItemModel.cpp \
    $$PWD/SubsystemInputConnectionMapModel.cpp \
    $$PWD/SubsystemOutputConnectionItemModel.cpp \
    $$PWD/SubsystemOutputConnectionMapModel.cpp \
    $$PWD/SystemItemModel.cpp \
    $$PWD/SystemMapModel.cpp \
    $$PWD/SystemModel.cpp \
    $$PWD/SystemXMLBaseModel.cpp \
    $$PWD/SystemXMLLoadModel.cpp \
    $$PWD/SystemXMLSaveModel.cpp \
    $$PWD/SystemErrorModel.cpp
